/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:35:28 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


//#import <CoreFoundation/CoreFoundation-Structs.h>
//@class NSArray;
//
//@interface NSUserDefaults : NSObject {
//
//	id _kvo_;
//	CFStringRef _identifier_;
//	CFStringRef _container_;
//	NSArray* _volatileDomainNames;
//
//}
//+(id)standardUserDefaults;
//+(void)setStandardUserDefaults:(id)arg1 ;
//+(void)resetStandardUserDefaults;
//+(id)_copyStandardUserDefaultsIfPresent;
//+(void)_web_defaultsDidChange;
//+(void)_web_addDefaultsChangeObserver;
//+(id)_web_preferredLanguageCode;
//-(void)registerDefaults:(id)arg1 ;
//-(float)floatForKey:(id)arg1 ;
//-(void)setInteger:(long long)arg1 forKey:(id)arg2 ;
//-(void)setDouble:(double)arg1 forKey:(id)arg2 ;
//-(void)setBool:(BOOL)arg1 forKey:(id)arg2 ;
//-(BOOL)boolForKey:(id)arg1 ;
//-(void)setLong:(long long)arg1 forKey:(id)arg2 ;
//-(BOOL)synchronize;
//-(id)stringForKey:(id)arg1 ;
//-(id)initWithUser:(id)arg1 ;
//-(void)removeObjectForKey:(id)arg1 ;
//-(double)doubleForKey:(id)arg1 ;
//-(long long)integerForKey:(id)arg1 ;
//-(id)dataForKey:(id)arg1 ;
//-(void)finalize;
//-(id)init;
//-(void)setFloat:(float)arg1 forKey:(id)arg2 ;
//-(void)setObject:(id)arg1 forKey:(id)arg2 inDomain:(id)arg3 ;
//-(id)URLForKey:(id)arg1 ;
//-(id)objectForKey:(id)arg1 ;
//-(void)setObject:(id)arg1 forKey:(id)arg2 ;
//-(void)dealloc;
//-(oneway void)release;
//-(id)valueForKey:(id)arg1 ;
//-(id)objectForKey:(id)arg1 inDomain:(id)arg2 ;
//-(id)initWithSuiteName:(id)arg1 ;
//-(id)arrayForKey:(id)arg1 ;
//-(long long)longForKey:(id)arg1 ;
//-(id)dictionaryRepresentation;
//-(void)setValue:(id)arg1 forKey:(id)arg2 ;
//-(id)dictionaryForKey:(id)arg1 ;
//-(void)_willBeginKeyValueObserving;
//-(void)_didEndKeyValueObserving;
//-(void)removeObjectForKey:(id)arg1 inDomain:(id)arg2 ;
//-(id)stringArrayForKey:(id)arg1 ;
//-(void)setURL:(id)arg1 forKey:(id)arg2 ;
//-(id)searchList;
//-(void)setSearchList:(id)arg1 ;
//-(void)addSuiteNamed:(id)arg1 ;
//-(void)removeSuiteNamed:(id)arg1 ;
//-(id)_initWithSuiteName:(id)arg1 container:(id)arg2 ;
//-(NSArray *)volatileDomainNames;
//-(id)volatileDomainForName:(id)arg1 ;
//-(void)setVolatileDomain:(id)arg1 forName:(id)arg2 ;
//-(void)removeVolatileDomainForName:(id)arg1 ;
//-(id)persistentDomainNames;
//-(id)persistentDomainForName:(id)arg1 ;
//-(void)setPersistentDomain:(id)arg1 forName:(id)arg2 ;
//-(void)removePersistentDomainForName:(id)arg1 ;
//-(BOOL)objectIsForcedForKey:(id)arg1 ;
//-(BOOL)objectIsForcedForKey:(id)arg1 inDomain:(id)arg2 ;
//-(CFStringRef)_identifier;
//-(void)_setIdentifier:(CFStringRef)arg1 ;
//-(CFStringRef)_container;
//-(void)_setContainer:(CFURLRef)arg1 ;
//-(id)_kvo;
//-(void)_setKVO:(id)arg1 ;
//-(NSArray *)volatileDomainNames;
//-(BOOL)_observingCFPreferences;
//@end
//
